"""SQLite data layer.

Stores three types of records used by the rest of the project:

  * articles - news articles fetched from RSS / web
  * posts    - Xiaohongshu drafts generated by the agents
  * metrics  - engagement data (impressions / likes / comments / ...) per post
  * events   - structured log of multi-agent orchestrator runs

The schema is intentionally small and dependency-free (only stdlib `sqlite3`)
so the project can run anywhere without extra infra.
"""

from __future__ import annotations

import json
import os
import sqlite3
import threading
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Iterator, Optional

DB_PATH = os.getenv("XHS_DB_PATH", "kb/xhs_agent.db")

_LOCK = threading.RLock()


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _ensure_parent(path: str) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)


SCHEMA = """
CREATE TABLE IF NOT EXISTS articles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    url TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    source TEXT,
    category TEXT,
    category_detected TEXT,
    score REAL DEFAULT 0,
    oneliner TEXT,
    snippet TEXT,
    published TEXT,
    fetched_at TEXT NOT NULL,
    used_for_post INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_articles_fetched_at ON articles(fetched_at);
CREATE INDEX IF NOT EXISTS idx_articles_score ON articles(score);

CREATE TABLE IF NOT EXISTS posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    topic TEXT,
    style TEXT,
    article_url TEXT,
    title TEXT,
    body TEXT NOT NULL,
    titles_candidates TEXT,
    titles_ranked TEXT,
    hashtags TEXT,
    status TEXT NOT NULL DEFAULT 'draft', -- draft | scheduled | published | failed
    platform TEXT DEFAULT 'xiaohongshu',
    platform_post_id TEXT,
    quality_score REAL DEFAULT 0,
    critic_feedback TEXT,
    created_at TEXT NOT NULL,
    scheduled_at TEXT,
    published_at TEXT,
    error TEXT
);

CREATE INDEX IF NOT EXISTS idx_posts_status ON posts(status);
CREATE INDEX IF NOT EXISTS idx_posts_scheduled ON posts(scheduled_at);

CREATE TABLE IF NOT EXISTS metrics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    fetched_at TEXT NOT NULL,
    impressions INTEGER DEFAULT 0,
    likes INTEGER DEFAULT 0,
    comments INTEGER DEFAULT 0,
    shares INTEGER DEFAULT 0,
    collects INTEGER DEFAULT 0,
    follows INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_metrics_post ON metrics(post_id);

CREATE TABLE IF NOT EXISTS events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id TEXT NOT NULL,
    ts TEXT NOT NULL,
    agent TEXT,
    level TEXT DEFAULT 'info',
    message TEXT,
    meta TEXT
);

CREATE INDEX IF NOT EXISTS idx_events_run ON events(run_id);
"""


@contextmanager
def get_conn(db_path: Optional[str] = None) -> Iterator[sqlite3.Connection]:
    """Return a sqlite3 connection with foreign_keys + WAL enabled."""
    path = db_path or DB_PATH
    _ensure_parent(path)
    with _LOCK:
        conn = sqlite3.connect(path, timeout=30, isolation_level=None)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys = ON")
        conn.execute("PRAGMA journal_mode = WAL")
        try:
            yield conn
        finally:
            conn.close()


def init_db(db_path: Optional[str] = None) -> None:
    """Create tables if missing. Safe to call any number of times."""
    with get_conn(db_path) as conn:
        conn.executescript(SCHEMA)


# ───────────────────────────── articles ─────────────────────────────


def upsert_article(article: dict) -> int:
    """Insert or update an article keyed by URL. Returns row id."""
    init_db()
    row = {
        "url": article["url"],
        "title": article.get("title", "")[:500],
        "source": article.get("source"),
        "category": article.get("category"),
        "category_detected": article.get("category_detected"),
        "score": float(article.get("score") or 0),
        "oneliner": article.get("oneliner"),
        "snippet": (article.get("snippet") or "")[:2000],
        "published": article.get("published"),
        "fetched_at": _now(),
    }
    with get_conn() as conn:
        cur = conn.execute(
            """
            INSERT INTO articles (url, title, source, category, category_detected,
                                  score, oneliner, snippet, published, fetched_at)
            VALUES (:url, :title, :source, :category, :category_detected,
                    :score, :oneliner, :snippet, :published, :fetched_at)
            ON CONFLICT(url) DO UPDATE SET
                title = excluded.title,
                source = excluded.source,
                category = excluded.category,
                category_detected = COALESCE(excluded.category_detected, articles.category_detected),
                score = MAX(excluded.score, articles.score),
                oneliner = COALESCE(excluded.oneliner, articles.oneliner),
                snippet = COALESCE(excluded.snippet, articles.snippet)
            """,
            row,
        )
        return cur.lastrowid or _article_id_by_url(conn, article["url"])


def _article_id_by_url(conn: sqlite3.Connection, url: str) -> int:
    r = conn.execute("SELECT id FROM articles WHERE url = ?", (url,)).fetchone()
    return int(r["id"]) if r else 0


def mark_article_used(url: str) -> None:
    with get_conn() as conn:
        conn.execute("UPDATE articles SET used_for_post = 1 WHERE url = ?", (url,))


def list_recent_articles(limit: int = 50) -> list[dict]:
    init_db()
    with get_conn() as conn:
        rows = conn.execute(
            "SELECT * FROM articles ORDER BY fetched_at DESC LIMIT ?", (limit,)
        ).fetchall()
        return [dict(r) for r in rows]


# ─────────────────────────────── posts ──────────────────────────────


def create_post(
    *,
    topic: Optional[str] = None,
    style: Optional[str] = None,
    article_url: Optional[str] = None,
    title: Optional[str] = None,
    body: str,
    titles_candidates: Optional[str] = None,
    titles_ranked: Optional[str] = None,
    hashtags: Optional[Iterable[str]] = None,
    status: str = "draft",
    scheduled_at: Optional[str] = None,
    quality_score: float = 0.0,
    critic_feedback: Optional[str] = None,
) -> int:
    init_db()
    row = {
        "topic": topic,
        "style": style,
        "article_url": article_url,
        "title": title,
        "body": body,
        "titles_candidates": titles_candidates,
        "titles_ranked": titles_ranked,
        "hashtags": json.dumps(list(hashtags or []), ensure_ascii=False),
        "status": status,
        "scheduled_at": scheduled_at,
        "quality_score": float(quality_score),
        "critic_feedback": critic_feedback,
        "created_at": _now(),
    }
    with get_conn() as conn:
        cur = conn.execute(
            """
            INSERT INTO posts (topic, style, article_url, title, body,
                               titles_candidates, titles_ranked, hashtags,
                               status, scheduled_at, quality_score, critic_feedback,
                               created_at)
            VALUES (:topic, :style, :article_url, :title, :body,
                    :titles_candidates, :titles_ranked, :hashtags,
                    :status, :scheduled_at, :quality_score, :critic_feedback,
                    :created_at)
            """,
            row,
        )
        return int(cur.lastrowid or 0)


def update_post(post_id: int, **fields: Any) -> None:
    if not fields:
        return
    cols = ", ".join(f"{k} = ?" for k in fields)
    values = list(fields.values()) + [post_id]
    with get_conn() as conn:
        conn.execute(f"UPDATE posts SET {cols} WHERE id = ?", values)


def get_post(post_id: int) -> Optional[dict]:
    with get_conn() as conn:
        r = conn.execute("SELECT * FROM posts WHERE id = ?", (post_id,)).fetchone()
        return dict(r) if r else None


def list_posts(status: Optional[str] = None, limit: int = 100) -> list[dict]:
    init_db()
    sql = "SELECT * FROM posts"
    args: tuple = ()
    if status:
        sql += " WHERE status = ?"
        args = (status,)
    sql += " ORDER BY created_at DESC LIMIT ?"
    args = args + (limit,)
    with get_conn() as conn:
        rows = conn.execute(sql, args).fetchall()
        return [dict(r) for r in rows]


def list_due_posts(now_iso: Optional[str] = None) -> list[dict]:
    """Scheduled posts whose `scheduled_at` is <= now and still 'scheduled'."""
    init_db()
    now_iso = now_iso or _now()
    with get_conn() as conn:
        rows = conn.execute(
            """
            SELECT * FROM posts
            WHERE status = 'scheduled' AND scheduled_at IS NOT NULL AND scheduled_at <= ?
            ORDER BY scheduled_at ASC
            """,
            (now_iso,),
        ).fetchall()
        return [dict(r) for r in rows]


# ───────────────────────────── metrics ──────────────────────────────


def add_metrics(
    post_id: int,
    *,
    impressions: int = 0,
    likes: int = 0,
    comments: int = 0,
    shares: int = 0,
    collects: int = 0,
    follows: int = 0,
) -> int:
    init_db()
    with get_conn() as conn:
        cur = conn.execute(
            """
            INSERT INTO metrics (post_id, fetched_at, impressions, likes,
                                 comments, shares, collects, follows)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (post_id, _now(), impressions, likes, comments, shares, collects, follows),
        )
        return int(cur.lastrowid or 0)


def latest_metrics_per_post() -> list[dict]:
    """Most recent metrics row for every post."""
    init_db()
    with get_conn() as conn:
        rows = conn.execute(
            """
            SELECT m.*, p.title, p.topic, p.status
            FROM metrics m
            JOIN posts p ON p.id = m.post_id
            WHERE m.id IN (
                SELECT MAX(id) FROM metrics GROUP BY post_id
            )
            ORDER BY m.fetched_at DESC
            """
        ).fetchall()
        return [dict(r) for r in rows]


# ───────────────────────────── events ───────────────────────────────


def log_event(
    run_id: str,
    agent: str,
    message: str,
    level: str = "info",
    meta: Optional[dict] = None,
) -> None:
    init_db()
    with get_conn() as conn:
        conn.execute(
            "INSERT INTO events (run_id, ts, agent, level, message, meta) VALUES (?, ?, ?, ?, ?, ?)",
            (
                run_id,
                _now(),
                agent,
                level,
                message,
                json.dumps(meta or {}, ensure_ascii=False),
            ),
        )


def list_events(run_id: Optional[str] = None, limit: int = 200) -> list[dict]:
    init_db()
    sql = "SELECT * FROM events"
    args: tuple = ()
    if run_id:
        sql += " WHERE run_id = ?"
        args = (run_id,)
    sql += " ORDER BY id DESC LIMIT ?"
    args = args + (limit,)
    with get_conn() as conn:
        return [dict(r) for r in conn.execute(sql, args).fetchall()]
